//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT
    {
        public int CSVReferenceNumber { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string TransactionReference { get; set; }
        public string AttorneyDocket { get; set; }
        public string Status { get; set; }
        public string TransactionID { get; set; }
        public string Type { get; set; }
        public string TotalPaymentRefund { get; set; }
        public string CustomerName { get; set; }
    }
}
