//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTD
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> PaymentDatePosted { get; set; }
        public Nullable<System.DateTime> SaleDatePosted { get; set; }
        public string SaleItemReference { get; set; }
        public string AttorneyDocket { get; set; }
        public string Status { get; set; }
        public string TransactionID { get; set; }
        public string SaleID { get; set; }
        public string FeeCode { get; set; }
        public string FeeCodeDescription { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public string CustomerName { get; set; }
    }
}
